### PR TITLE
Added init-scripts to help people initialise their virtual servers.

### PR DESCRIPTION
**Pull request by narun4sk**
TODO: Ansible playbook

### CODE REVIEW

**Comment by sirex** [comment]
First of all `cn_mkfs.log` probably should not be kept under version control?

Second, it looks like Docker reinvention?

And talking about containers, I have tried to run few projects inside Docker containers, and it caused many problems, those problems where related not with Docker itself bet with the containerisation.

Easiest thing to test deployments is Vagrant. It just few lines of configuration and integrates well with Ansible (or anything else). Just take a look at [this configuration file](https://github.com/akllt/infrastructure/blob/master/websites/pylab.lt/Vagrantfile).

Vagrant proved to be rock solid on number of projects that I worked with. Mostly it just forks. So I would be happy to maintain and use deployment testing environment based on Vagrant, probably Docker based version would be also OK, but I would not like to use and maintain your home grown containerization scripts, that I'm not familiar with and don't see point to spent time on familiarizing with it.

So I think it would be better to use Vagrant, unless you tell me real good reason why we should use these scripts, instead of Vagrant.

**Comment by narun4sk** [comment]
> First of all cn_mkfs.log probably should not be kept under version control?

At least one reason why not?

> Second, it looks like Docker reinvention?

Nope, not at all... Docker however to my knowledge is based on [LXC](https://linuxcontainers.org), so from this point of view my implementation is similar... Vagrant in other hand stands on the shoulder of [virtualbox](https://www.virtualbox.org) - just a different kind of virtualisation... On top of that, [virtualbox](https://www.virtualbox.org) is a _Hypervisor_, ultimately this means - resource hungry...

> And talking about containers, I have tried to run few projects inside Docker containers, and it caused many problems, those problems where related not with Docker itself bet with the containerisation.

I wonder what those were? Are you sure you shouldn't blame yourself more rather than the _containers_?

> Easiest thing to test deployments is Vagrant. It just few lines of configuration and integrates well with Ansible (or anything else). Just take a look at this configuration file.

Do you mean this is your preferred way to test deployments?

> Vagrant proved to be rock solid on number of projects that I worked with. Mostly it just forks. So I would be happy to maintain and use deployment testing environment based on Vagrant, probably Docker based version would be also OK, but I would not like to use and maintain your home grown containerization scripts, that I'm not familiar with and don't see point to spent time on familiarizing with it.

Well that's just your personal preferences. I personally would rather not spend more time discovering _Vagrant_... Come on, who on this world told you that you have to maintain my scripts?? Remember, this is **not** your personal project, we work together on this, well at least until this minute I was sure we do.

Last but not least, my scripts does just 4 main operations:

```
dd if=/dev/zero bs=1M count=1 seek="$_sz" of="${_imgpath}"
mke2fs -t "${_fstype}" -m0 -L "${_name}" "${_imgpath}"
mount -v -t ${_fstype} ${_fs} ${_mnt}
debootstrap --include=openssh-server,rsync "${_system}" "${_mnt}" "${_cnsrc}"
```

The rest was to make scripts readable (vastly commented), separate them to logical blocks (3 scripts in total) and make them verbose, so that every **noob** on the planet could easily understand, what is going on under the bonnet...

Further, once my scripts finish their dirty work, it's up to you, how you start your containers. If you are on the older system - please install 2 packages:

```
# apt-get install lxc bridge-utils
```

If that's a modern one, as `Debian Jessie` or `Archlinux`, you don't need to install a shit, just use `systemd-nspawn -D ${_mnt}`.

I hope I've proved my point :)

PS:
We are not in the agile development. We are just trying to make things work the best way we can, aren't we?

**Comment by sirex** [comment]
> > Easiest thing to test deployments is Vagrant. It just few lines of configuration and integrates well with Ansible (or anything else). Just take a look at this configuration file.
> 
> Do you mean this is your preferred way to test deployments?

Yes, I prefer 4 lines of clean and high level Vagrant configuration:

``` ruby
box.vm.box = 'ubuntu/trusty64'
box.vm.network :forwarded_port, guest: 80, host: 8080
box.vm.network :private_network, ip: "10.0.0.42"
box.vm.synced_folder '.', '/vagrant', disabled: true
```

with [good documentation](https://docs.vagrantup.com/v2/getting-started/) over your custom shell scripts with low level containerization implementation.

> Come on, who on this world told you that you have to maintain my scripts??
> 
> Remember, this is **not** your personal project, we work together on this, well at least until this minute I was sure we do.

Since we work together on this project, each and every line of code in our repository is maintained by everyone in the team.

So as I said, I don't mind clean and high level configuration with good documentation.

But this:

``` bash
dd if=/dev/zero bs=1M count=1 seek="$_sz" of="${_imgpath}"
mke2fs -t "${_fstype}" -m0 -L "${_name}" "${_imgpath}"
mount -v -t ${_fstype} ${_fs} ${_mnt}
debootstrap --include=openssh-server,rsync "${_system}" "${_mnt}" "${_cnsrc}"
```

is low level, hard to read and maintain shell scripting that is going to cost a lot of time in the long run.

Anyway, if you don't trust my opinion, that is OK, you have to get this experience yourself. Before accepting this pull request I would like to ask you to finish it first.

What we need is a possibility to test Ansible deployment configuration.

What you have now, is just a possibility to create a container where the deployment testing will happens. So far, you can achieve same goal with Docker using single command:

```
$ docker run -it debian:wheezy bash
```

Or Vagrant, using two commands:

```
$ vagrant init debian/wheezy64
$ vagrant up
```

Now you need to add [this Ansible configuration](https://github.com/akllt/infrastructure/blob/master/websites/pylab.lt/deploy.yml), adjust it to our project needs and test it inside a container or a virtual machine. Virtual machine must run Ubutnu 14.04, because we have Ubuntu 14.00 in AKL servers, deployment testing should be close to production.

The final result is the ability to see working deployment by visiting IP address of virtual machine in a browser.

I just want you to know, that this can be done with following Vagrantfile:

``` ruby
Vagrant.require_version ">= 1.6"

Vagrant.configure('2') do |config|
  config.vm.define 'box' do |box|
    box.vm.box = 'ubuntu/trusty64'
    box.vm.network :forwarded_port, guest: 80, host: 8080
    box.vm.network :private_network, ip: "10.0.0.42"
    box.vm.synced_folder '.', '/vagrant', disabled: true
  end
end
```

And single command:

```
$ vagrant up
```

But of course, you can do it your own way, but just try to keep it simple, deployment testing is really least important thing in this project.

**Comment by sirex** [comment]
By the way, Vagrant also supports [lxc](https://github.com/fgrehm/vagrant-lxc) and [docker](http://docs.vagrantup.com/v2/docker/index.html).

**Comment by narun4sk** [comment]
> Now you need to add this Ansible configuration, adjust it to our project needs and test it inside a container or a virtual machine. Virtual machine must run Ubutnu 14.04, because we have Ubuntu 14.00 in AKL servers, deployment testing should be close to production.

Ho ho ho, captain obvious! Since when I need?

With such an attitude you will find yourself alone in this project.

**Comment by narun4sk** [comment]
> The final result is the ability to see working deployment by visiting IP address of virtual machine in a browser.

Do you really think, that I'm stupid enough to write a few hundred lines in `bash` just to listen to someone teaching me that the final goal was to enter the IP address in the browser and see something??

> I just want you to know, that this can be done with following Vagrantfile:

``` ruby
Vagrant.require_version ">= 1.6"

Vagrant.configure('2') do |config|
  config.vm.define 'box' do |box|
    box.vm.box = 'ubuntu/trusty64'
    box.vm.network :forwarded_port, guest: 80, host: 8080
    box.vm.network :private_network, ip: "10.0.0.42"
    box.vm.synced_folder '.', '/vagrant', disabled: true
  end
end
```

Well,  I just want you to know, that your Vagrant config is just one line less than mine LXC config (excluding comments and blank lines). Or no config file at all, in case of _systemd_...

```
# For additional config options, please look at lxc.container.conf(5)
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = br0
lxc.network.hwaddr = 4a:49:43:49:79:44
lxc.rootfs = /home/containers/ubnt/mount

# Common configuration
lxc.include = /usr/share/lxc/config/debian.common.conf

# Container specific configuration
lxc.utsname = ubnt
lxc.arch = amd64
lxc.autodev = 1
lxc.kmsg = 0
```

`dd`, `mke2fs`, `mount`, `debootstrap` - 3 out of 4 are the standard linux commands/tools, what kind of documentation do you need? I can copy-paste the manual pages, if that would help...

**Comment by sirex** [comment]
> Ho ho ho, captain obvious! Since when I need?

Since we agreed on this during sprint planing. See #6.

> With such an attitude you will find yourself alone in this project.

We agreed to use SCRUM for project management, I invited you to create product backlog _together_, then _together_ we did sprint planning and _together_ we agreed on tasks and how exactly we going to implement them. What you are doing here is something, that was not discussed and was not agreed in sprint planning.

This pull request looks like an alternative implementation of #6 task?  And #6 task tells:

> What you need to do is to fork https://github.com/akllt/infrastructure
> and copy for example websites/pylab.lt to websites/ubuntu.lt and
> replace everything related to pylab to ubuntu analog.

If you can't follow basic project and team management discipline, then it can be hard to go further.

Anyway, lets assume, that somehow you missed #6 task during sprint planning. In this case we can repeat sprint planing just for #1 user story.

Could you describe in more detail how you going to implement #1 user story?

> Do you really think, that I'm stupid enough to write a few hundred lines in bash just to listen to someone teaching me that the final goal was to enter the IP address in the browser and see something??

Please, explain, what is you final goal with these shell scripts?

Did you tried to look at suggested [implementation](https://github.com/akllt/infrastructure/tree/master/websites/pylab.lt). If yes, then what issues did you found?

**Comment by narun4sk** [comment]
I'm glad you have mentioned #6, since I don't see where we agreed?? I can see your guidelines yes, but that's just that.. Where do I confirm that I love Vagrant I think this is the way to go? Like I said, this is your personal preference and I find it surprising that you think that the fact you post things in the issues means that we agree on something...

Now back to reality, this is what we agreed. Let me quote you from #1:

> If we will use one of AKL servers, then deployment scripts should be taken from one of these examples

Then from #7:

> sorry, I meant your. Could you post IP address of your server so I could point new.ubuntu.lt to your server.

Well that's what we have definitely agreed... So I don't see how does that boils down to the Vagrant please?

> If you can't follow basic project and team management discipline, then it can be hard to go further.
> 
> Anyway, lets assume, that somehow you missed #6 task during sprint planning. In this case we can repeat sprint planing just for #1 user story.

Well to my knowledge so far I am following the project as close as possible, but what about you?

> Please, explain, what is you final goal with these shell scripts?

There is not much to explain. This is my way of initializing development environment, even if this does not match your personal preferences or experiences. You love Vagrant, I get it, so please implement your scripts, but please, you don't tell me that I need to waste more of my time just match your preferences, especially when we agreed otherwise in the project...

> Did you tried to look at suggested implementation. If yes, then what issues did you found?

I did not, as I said in #1, I don't think this is essential to the project nor I think is needed.
I have agreed to implement Ansible playbook, which is also mentioned in the comments of my commit and I reckon has some potential in the deployments, but that's just that.

**Comment by sirex** [comment]
OK, I see miscommunication and lack of experience in SCRUM mixed with hot temperament... :)

In SCRUM you can't write code for user story. User story is just an abstract idea about what is needed, but not how it should be done.

That is why I created #6 task with very specific implementation details for #1 user story.

I assigned #6 task to you, you received email, had no comments, I announce the end of sprint planning, so that means, we agreed on implementation.

Then you created pull request, since implementation of pull request can't be based on user story or comments in user story, it should be based on task definition with implementation details discussed during sprint planning. That is why I naturally assumed, that you are working on #6 task according to task description.

So user stories is just an idea what is needed, anyone at any time can create user stories, but you can't write code for user stories without tasks created during sprint planning. Tasks should be based on a user story and should provide very specific implementation details, discussed during sprint planning.

Regarding your implementation, I will write after lunch.

**Comment by sirex** [comment]
So, regarding your implementation, since you will host ubuntu.lt demo on your own server, you are free to do anything you want with your server as long as it works.

Your server will be used only for demo purposes and when we finish development, final ubuntu.lt production version will be hosted on AKL servers as it was for about 10 years. Each deployment to AKL server have to maintain some level of consistency, that is why I pointed you to an example how it should be done.

So #6 task will have to be implemented as described anyway, before production deployment.

But if you would like to have alternate deployment testing just for demo server, that is fine with me and #6 task can be postponed.

Before continuing with the code, please describe how you going to do this in a new task, probably I will have some comments, and when we agree on implementation details, you can take that task and implement it.

**Pull request closed without merging**
